# sudo apt install software-properties-common -y
# sudo add-apt-repository --yes --update ppa:ansible/ansible
# sudo apt install ansible -y
# ansible --version

# ansible -i inventory/hosts.ini all -m ping
# ansible-playbook -i inventory/hosts.ini playbook/server-complaince.yaml
# ansible-playbook -i inventory/hosts.ini playbook/server-complaince.yaml --syntax-check
# showing (playbook: playbook/server-complaince.yaml)
# ansible-playbook -i inventory/hosts.ini playbook/server-complaince.yaml



---
applications:
  - name: nginx
    version_command: "nginx -v"

  - name: docker
    version_command: "docker --version"

  - name: python
    version_command: "python3 --version"

  - name: git
    version_command: "git --version"

  - name: node
    version_command: "node --version"

  - name: terraform
    version_command: "terraform --version"

  - name: java
    version_command: "java --version"