[servers]

ansible-playbook-01 ansible_host=20.64.226.68 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/ansible-playbook-01_key.pem
ansible-playbook-02 ansible_host=52.233.89.238 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/ansible-playbook-02_key.pem